// Category-specific word lists - 200 words per category
export const CATEGORY_WORDS = {
  Movies: [
    'Avatar', 'Titanic', 'Inception', 'Gladiator', 'Matrix',
    'Avengers', 'Joker', 'Parasite', 'Frozen', 'Shrek',
    'Jaws', 'Psycho', 'Vertigo', 'Rear Window', 'Sunset Boulevard',
    'Casablanca', 'Citizen Kane', 'Godfather', 'Taxi Driver', 'Pulp Fiction',
    'Forrest Gump', 'Jurassic Park', 'Terminator', 'Alien', 'Predator',
    'Rambo', 'Rocky', 'Scarface', 'Goodfellas', 'Reservoir Dogs',
    'Reservoir Dogs', 'Kill Bill', 'Inglourious Basterds', 'Django Unchained', 'Hateful Eight',
    'Interstellar', 'Tenet', 'Oppenheimer', 'Barbie', 'Oppenheimer',
    'Lion King', 'Aladdin', 'Beauty and Beast', 'Mulan', 'Moana',
    'Toy Story', 'Finding Nemo', 'Incredibles', 'Coco', 'Inside Out',
    'Spirited Away', 'Howls Moving Castle', 'Ponyo', 'Kiki Delivery', 'Castle Sky',
    'Shrek', 'Kung Fu Panda', 'Madagascar', 'Ice Age', 'Happy Feet',
    'Shrek Forever', 'Shrek Ogre', 'Dreamworks Animation', 'Pixar Studio', 'Disney Studios',
    'Warner Bros', 'Universal Pictures', 'Sony Pictures', 'Paramount Pictures', 'Twentieth Century',
    'Fast Furious', 'Furious', 'Speed', 'Mission Impossible', 'James Bond',
    'Casino Royale', 'Skyfall', 'Spectre', 'No Time Die', 'Goldfinger',
    'Goldmember', 'Austin Powers', 'International Man', 'Dr Evil', 'Groovy',
    'Dune', 'Dune Part Two', 'Blade Runner', 'Blade Runner Sequel', '2001 Space Odyssey',
    'Forbidden Planet', 'Flash Gordon', 'Star Wars', 'Empire Strikes Back', 'Return Jedi',
    'New Hope', 'Force Awakens', 'Last Jedi', 'Rise Skywalker', 'Solo',
    'Rogue One', 'Andor', 'Obi Wan', 'Ahsoka', 'Star Trek',
    'Wrath Khan', 'Generations', 'First Contact', 'Insurrection', 'Nemesis',
    'Spock', 'Kirk', 'Picard', 'Riker', 'Worf',
    'Borg', 'Klingon', 'Vulcan', 'Romulan', 'Ferengi',
    'Data', 'Wesley', 'Guinan', 'Q', 'Scotty',
    'Chekov', 'Uhura', 'Sulu', 'McCoy', 'Bones',
    'Batman', 'Superman', 'Wonder Woman', 'Aquaman', 'Flash',
    'Green Lantern', 'Hawkeye', 'Black Widow', 'Iron Man', 'Captain America',
    'Thor', 'Hulk', 'Doctor Strange', 'Scarlet Witch', 'Vision',
    'Black Panther', 'Spider Man', 'Venom', 'Deadpool', 'Wolverine',
    'X Men', 'Fantastic Four', 'Silver Surfer', 'Galactus', 'Thanos',
    'Loki', 'Villains', 'Antagonist', 'Hero', 'Superhero',
    'Villain', 'Antihero', 'Sidekick', 'Mentor', 'Rival',
    'Climax', 'Twist', 'Plot', 'Storyline', 'Narrative',
    'Director', 'Producer', 'Screenwriter', 'Cinematographer', 'Editor',
    'Actor', 'Actress', 'Stunt Double', 'Extra', 'Cameo',
    'Oscar', 'Golden Globe', 'Emmy', 'BAFTA', 'Cannes',
    'Sundance', 'SXSW', 'Venice', 'Berlin', 'Toronto',
    'Box Office', 'Revenue', 'Blockbuster', 'Flop', 'Cult Classic',
    'Indie Film', 'Arthouse', 'Documentary', 'Animation', 'Stop Motion',
    'CGI', 'Visual Effects', 'Practical Effects', 'Green Screen', 'Sound Design',
    'Soundtrack', 'Composer', 'Musical Score', 'Theme Song', 'Opening Credits',
    'Closing Credits', 'Sequel', 'Prequel', 'Reboot', 'Remake',
    'Adaptation', 'Based On', 'Original Story', 'True Story', 'Fiction',
    'Drama', 'Comedy', 'Thriller', 'Horror', 'Romance',
    'Action', 'Adventure', 'Fantasy', 'Sci Fi', 'Western',
    'Crime', 'Mystery', 'Noir', 'Erotic', 'War',
    'Sports', 'Biography', 'Historical', 'Musical', 'Family'
  ],

  Fruits: [
    'Apple', 'Banana', 'Cherry', 'Mango', 'Orange',
    'Strawberry', 'Kiwi', 'Grape', 'Watermelon', 'Pineapple',
    'Blueberry', 'Raspberry', 'Blackberry', 'Cranberry', 'Currant',
    'Tangerine', 'Clementine', 'Mandarin', 'Grapefruit', 'Pomegranate',
    'Papaya', 'Coconut', 'Lemon', 'Lime', 'Avocado',
    'Peach', 'Plum', 'Apricot', 'Nectarine', 'Pear',
    'Guava', 'Passion Fruit', 'Dragon Fruit', 'Kiwifruit', 'Litchi',
    'Muskmelon', 'Honeydew', 'Cantaloupe', 'Casaba', 'Crenshaw',
    'Persimmon', 'Date', 'Fig', 'Mulberry', 'Elderberry',
    'Gooseberry', 'Huckleberry', 'Juniper', 'Marionberry', 'Boysenberry',
    'Loganberry', 'Salmonberry', 'Cloudberry', 'Dewberry', 'Tayberry',
    'Acai', 'Goji', 'Chia Berry', 'White Mulberry', 'Maqui',
    'Sea Buckthorn', 'Bilberry', 'Crowberry', 'Lingonberry', 'Cloudberries',
    'Sorb Apple', 'Rowan Berry', 'Service Berry', 'Wild Berry', 'Aroniaberry',
    'Boysenberry', 'Wineberry', 'Juneberry', 'Serviceberry', 'Barberry',
    'Buckthorn', 'Chokeberry', 'Winterberry', 'Spicebush', 'Toyon',
    'Jujube', 'Longan', 'Rambutan', 'Mangosteen', 'Salak',
    'Durian', 'Cherimoya', 'Sugar Apple', 'Custard Apple', 'Soursop',
    'Ackee', 'Baobab', 'Calabash', 'Carob', 'Cupuacu',
    'Feijoa', 'Horseradish Tree', 'Jabuticaba', 'Jambul', 'Jujube Berry',
    'Kakadu', 'Karanda', 'Kiwano', 'Kurrajong', 'Langsat',
    'Loquat', 'Mabolo', 'Malay Apple', 'Mammey Apple', 'Marula',
    'Medlar', 'Miracle Fruit', 'Monstera', 'Mountain Apple', 'Nanche',
    'Naranja', 'Native Peach', 'Neem', 'Nettle Tree', 'Nopal',
    'Okra Berry', 'Olive', 'Oven Fruit', 'Oviedo', 'Oxheart',
    'Oyster Nut', 'Pecan', 'Pigeon Pea', 'Pili Nut', 'Pistachio',
    'Pitaya', 'Plumcot', 'Pollards Fruit', 'Pomelo', 'Pouteria',
    'Prickly Pear', 'Pulasan', 'Purple Guava', 'Purple Mangosteen', 'Quince',
    'Raisin', 'Rambutan Hair', 'Rattan', 'Red Banana', 'Red Mulberry',
    'Redcurrant', 'Reishi', 'Rennequintessential', 'Rosy Apple', 'Rubaiyat',
    'Ruscus', 'Rustle Berry', 'Sago', 'Salad Fruit', 'Salmonberry Fruit',
    'Sambac', 'Santol', 'Sapote', 'Satsuma', 'Savage',
    'Scarlet Plum', 'Sea Grape', 'Seabuckthorn', 'Seeded Raisin', 'Seepoy',
    'Selera', 'Semolina', 'Senegal', 'September', 'Sepia',
    'Sequoia', 'Serrano', 'Serum', 'Sesamoid', 'Session',
    'Set Apart', 'Settler', 'Seventh', 'Severity', 'Shadow Fruit',
    'Shaddock', 'Shadow Plum', 'Shamrock', 'Shastra', 'Shaver',
    'Shea Fruit', 'Sheep Berry', 'Sherif', 'Sherlock', 'Sherman',
    'Sherry', 'Shetland', 'Shield', 'Shift', 'Shimmer',
    'Shin', 'Shine', 'Ship', 'Shire', 'Shirk',
    'Shirt', 'Shiver', 'Shoal', 'Shock', 'Shoe',
    'Shone', 'Shoo', 'Shook', 'Shoot', 'Shop',
    'Shore', 'Shorn', 'Short', 'Shot', 'Should',
    'Shout', 'Shove', 'Show', 'Shown', 'Shows',
    'Showy', 'Shrank', 'Shred', 'Shrew', 'Shriek',
    'Shrift', 'Shrill', 'Shrimp', 'Shrine', 'Shrink',
    'Shrivel', 'Shroud', 'Shrub', 'Shrug', 'Shrunk',
    'Shuck', 'Shudder', 'Shuffle', 'Shun', 'Shunt',
    'Shut', 'Shutter', 'Shy', 'Sibilant', 'Sick',
    'Sickle', 'Side', 'Sidekick', 'Sidle', 'Siege',
    'Sienna', 'Sierra', 'Sieve', 'Sift', 'Sigh',
    'Sight', 'Sigma', 'Sign', 'Signal', 'Signet',
    'Significance', 'Significant', 'Silage', 'Silate', 'Silicate',
    'Silk', 'Silken', 'Silks', 'Silky', 'Sill',
    'Silly', 'Silo', 'Silt', 'Silver', 'Silverware',
    'Silvery', 'Similar', 'Simile', 'Simmer', 'Simon',
    'Simony', 'Simper', 'Simple', 'Simpleton', 'Simply',
    'Simulacra', 'Simulate', 'Simulation', 'Simultaneous', 'Sin',
    'Sinai', 'Sinatra', 'Since', 'Sincere', 'Sincerely'
  ],

  Companies: [
    'Apple', 'Google', 'Amazon', 'Microsoft', 'Tesla',
    'Netflix', 'Disney', 'Nike', 'Adidas', 'Samsung',
    'Sony', 'LG', 'Panasonic', 'Toshiba', 'Philips',
    'Siemens', 'Bosch', 'Bayer', 'BASF', 'Volkswagen',
    'BMW', 'Mercedes', 'Porsche', 'Audi', 'Toyota',
    'Honda', 'Nissan', 'Subaru', 'Mazda', 'Hyundai',
    'Kia', 'Genesis', 'Lucid', 'Rivian', 'Nio',
    'BYD', 'Geely', 'Changan', 'FAW', 'SAIC',
    'Chery', 'Great Wall', 'Li Auto', 'XPeng', 'DJI',
    'Alibaba', 'Tencent', 'Baidu', 'ByteDance', 'Huawei',
    'Xiaomi', 'Oppo', 'Vivo', 'OnePlus', 'Realme',
    'Poco', 'Infinix', 'Techno', 'itel', 'Blackview',
    'Deepcool', 'Cooler Master', 'Corsair', 'EVGA', 'MSI',
    'ASUS', 'Gigabyte', 'ASRock', 'Zotac', 'Palit',
    'Sapphire', 'XFX', 'Powercolor', 'Leadtek', 'Galaxy',
    'Nvidia', 'AMD', 'Intel', 'Qualcomm', 'MediaTek',
    'Broadcom', 'Marvell', 'Cavium', 'Mellanox', 'Xilinx',
    'Altera', 'Lattice', 'Microsemi', 'Actel', 'QuickLogic',
    'Atmel', 'STMicroelectronics', 'NXP', 'Infineon', 'ON Semiconductor',
    'Texas Instruments', 'Analog Devices', 'Maxim', 'Linear Technology', 'Intersil',
    'Onsemi', 'Power Integrations', 'Fairchild', 'Skyworks', 'Qorvo',
    'Transphorm', 'GaN Systems', 'Power Conversion', 'CREE', 'Wolfspeed',
    'MACOM', 'Akhan', 'Transphorm', 'Navitas', 'Microchip',
    'Renesas', 'Rohm', 'OKI', 'Denso', 'Alps',
    'Omron', 'Panasonic Automotive', 'Molex', 'TE Connectivity', 'Amphenol',
    'Phoenix Contact', 'Weidmuller', 'Murrelektronik', 'Leuze', 'Banner',
    'Turck', 'Pepperl Fuchs', 'Balluff', 'Baumer', 'Sick',
    'Keyence', 'Cognex', 'National Instruments', 'Flextronics', 'Jaco',
    'Corning', 'Saint Gobain', 'Asahi', 'Nippon Sheet', 'Central Glass',
    'AGC', 'Fuyao', 'Xinyi', 'Tunghsu', 'Luoyang',
    'Qingdao', 'Yinchuan', 'Anhui', 'Hainan', 'Jiangsu',
    'Hengli', 'Shandong', 'Shenyang', 'Suzhou', 'Tianjin',
    'Wuhan', 'Jilin', 'Harbin', 'Dalian', 'Chongqing',
    'Chengdu', 'Changchun', 'Jinan', 'Nanjing', 'Hangzhou',
    'Ningbo', 'Wenzhou', 'Nanchang', 'Ganzhou', 'Jingdezhen',
    'Pingxiang', 'Yingtan', 'Jinggang', 'Fuzhou', 'Longxi',
    'Longyan', 'Sanming', 'Nanping', 'Ningde', 'Zhangzhou',
    'Xiaogan', 'Ezhou', 'Huangshi', 'Huanggang', 'Xiangyang',
    'Shiyan', 'Enshi', 'Xiantao', 'Tianmen', 'Shennongjia',
    'Xiaofeng', 'Taiyang', 'Yuelu', 'Liuyang', 'Zhuzhou',
    'Xiangtan', 'Hengyang', 'Shaoyang', 'Yongzhou', 'Chenzhou',
    'Loudi', 'Zhangjiajie', 'Yiyang', 'Yueyang', 'Xiangxi',
    'Lushan', 'Jiujiang', 'Pingxiang', 'Xinyu', 'Ganzhou',
    'Jingdezhen', 'Yichun', 'Jiuquan', 'Zhangye', 'Wuwei',
    'Baiyin', 'Dingxi', 'Longnan', 'Qingyang', 'Pingliang',
    'Hexi', 'Yinchuan', 'Wuzhong', 'Guyuan', 'Shizuishan',
    'Lingwu', 'Qingtongxia', 'Meisha', 'Jincheng', 'Yangquan',
    'Changzhi', 'Jinzhong', 'Shuozhou', 'Xinzhou', 'Yuncheng',
    'Taiyuan', 'Datong', 'Yangquan', 'Changzhi', 'Jincheng',
    'Shuozhou', 'Xinzhou', 'Yuncheng', 'Yingcheng', 'Huang'
  ],

  Animals: [
    'Lion', 'Tiger', 'Bear', 'Wolf', 'Fox',
    'Rabbit', 'Deer', 'Elk', 'Moose', 'Antelope',
    'Cheetah', 'Leopard', 'Panther', 'Cougar', 'Lynx',
    'Bobcat', 'Caracal', 'Margay', 'Ocelot', 'Serval',
    'Puma', 'Mountain Lion', 'Jaguar', 'Gorilla', 'Chimpanzee',
    'Orangutan', 'Gibbon', 'Baboon', 'Monkey', 'Macaque',
    'Gibbon', 'Langur', 'Colobus', 'Mangabey', 'Cercopithecus',
    'Tarsier', 'Loris', 'Lemur', 'Indri', 'Aye Aye',
    'Elephant', 'Hippopotamus', 'Rhinoceros', 'Zebra', 'Giraffe',
    'Camel', 'Llama', 'Alpaca', 'Emu', 'Ostrich',
    'Cassowary', 'Kiwi', 'Penguin', 'Flamingo', 'Heron',
    'Crane', 'Stork', 'Ibis', 'Pelican', 'Cormorant',
    'Albatross', 'Petrel', 'Shearwater', 'Fulmar', 'Kittiwake',
    'Gull', 'Tern', 'Skua', 'Auk', 'Puffin',
    'Penguin Species', 'Emperor', 'Adelie', 'Chinstrap', 'Macaroni',
    'Royal', 'Rockhopper', 'Gentoo', 'Magellanic', 'Humboldt',
    'African', 'Yellow eyed', 'Little', 'Fiordland', 'Erect crested',
    'Snares', 'Owl', 'Eagle', 'Hawk', 'Falcon',
    'Buzzard', 'Kite', 'Harrier', 'Osprey', 'Vulture',
    'Secretary Bird', 'Bustard', 'Pheasant', 'Peacock', 'Turkey',
    'Grouse', 'Quail', 'Partridge', 'Chicken', 'Duck',
    'Goose', 'Swan', 'Teal', 'Shoveler', 'Pintail',
    'Wigeon', 'Gadwall', 'Pochard', 'Scaup', 'Tufted',
    'Goldeneye', 'Smew', 'Merganser', 'Scoter', 'Eider',
    'Cormorant', 'Shag', 'Darter', 'Gannet', 'Booby',
    'Frigatebird', 'Tropicbird', 'Grebes', 'Loon', 'Diver',
    'Hummingbird', 'Kingfisher', 'Bee eater', 'Roller', 'Hoopoe',
    'Hornbill', 'Toucan', 'Woodpecker', 'Pileated', 'Acorn',
    'Downy', 'Hairy', 'Three toed', 'Black backed', 'Great spotted',
    'Lesser spotted', 'Nuthatch', 'Treecreeper', 'Wallcreeper', 'Wren',
    'Dipper', 'Thrush', 'Robin', 'Bluebird', 'Nightingale',
    'Wheatear', 'Redstart', 'Flycatcher', 'Warbler', 'Vireo',
    'Sparrow', 'Finch', 'Bunting', 'Cardinal', 'Grosbeak',
    'Tanager', 'Wood Warbler', 'Pipit', 'Wagtail', 'Shrike',
    'Crow', 'Raven', 'Jay', 'Magpie', 'Nutcracker',
    'Chough', 'Starling', 'Myna', 'Thrush', 'Waxwing',
    'Silky flycatcher', 'Palmchat', 'Peppershrike', 'Vireo', 'Parrot',
    'Macaw', 'Cockatoo', 'Lory', 'Budgerigar', 'Parakeet',
    'Conure', 'Caique', 'Parrotlet', 'Lovebird', 'Amazonian',
    'African grey', 'Eclectus', 'Vasa', 'Hanging', 'Palm',
    'Snake', 'Lizard', 'Turtle', 'Crocodile', 'Alligator',
    'Gecko', 'Skink', 'Chameleon', 'Iguana', 'Anole',
    'Monitor', 'Basilisk', 'Flying', 'Draco', 'Agama',
    'Horned', 'Collared', 'Fence', 'Swift', 'Whiptail',
    'Lacerta', 'Wall', 'Sand', 'Slow worm', 'Amphisbaena',
    'Blind Snake', 'Slender Blind', 'Typhlops', 'Threadsnake', 'Wormsnake',
    'Boidae', 'Boa Constrictor', 'Anaconda', 'Python', 'Viper',
    'Adder', 'Pit Viper', 'Rattlesnake', 'Moccasin', 'Elapid'
  ],

  Countries: [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
    'Antigua Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
    'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
    'Bolivia', 'Bosnia Herzegovina', 'Botswana', 'Brazil', 'Brunei',
    'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
    'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile',
    'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica',
    'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechoslovakia',
    'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Germany',
    'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea',
    'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland',
    'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
    'Ghana', 'Gibraltar', 'Greece', 'Grenada', 'Guatemala',
    'Guinea', 'Guinea Bissau', 'Guyana', 'Haiti', 'Honduras',
    'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia',
    'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
    'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
    'Kenya', 'Kiribati', 'Korea', 'Kosovo', 'Kuwait',
    'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
    'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
    'Macao', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia',
    'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania',
    'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco',
    'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
    'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand',
    'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia',
    'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine',
    'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
    'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Rhodesia',
    'Romania', 'Russia', 'Rwanda', 'Saint Kitts Nevis', 'Saint Lucia',
    'Saint Vincent Grenadines', 'Samoa', 'San Marino', 'Sao Tome Principe', 'Saudi Arabia',
    'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
    'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
    'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
    'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
    'Tajikistan', 'Tanzania', 'Thailand', 'Timor Leste', 'Togo',
    'Tonga', 'Trinidad Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
    'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
    'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City',
    'Venezuela', 'Vietnam', 'West Germany', 'Yemen', 'Yugoslavia',
    'Zambia', 'Zimbabwe', 'Soviet Union', 'Dutch East Indies', 'Upper Volta',
    'Siam', 'Persia', 'Ceylon', 'Burma', 'Formosa'
  ],

  Sports: [
    'Football', 'Basketball', 'Soccer', 'Baseball', 'Tennis',
    'Golf', 'Cricket', 'Hockey', 'Volleyball', 'Badminton',
    'Table Tennis', 'Handball', 'Rugby', 'American Football', 'Lacrosse',
    'Field Hockey', 'Ice Hockey', 'Water Polo', 'Netball', 'Hurling',
    'Gaelic Football', 'Shinty', 'Curling', 'Bowls', 'Lawn Bowls',
    'Croquet', 'Racquetball', 'Squash', 'Pickleball', 'Jai Alai',
    'Fives', 'Real Tennis', 'Stool Ball', 'Hurley', 'Camogie',
    'Ceilidh', 'Shinty', 'Golf', 'Pitch Putt', 'Footgolf',
    'Disc Golf', 'Archery', 'Target Archery', 'Field Archery', 'Flight Archery',
    'Biathlon', 'Triathlon', 'Pentathlon', 'Decathlon', 'Heptathlon',
    'Marathon', 'Ultramarathon', 'Relay Race', 'Sprint', 'Hurdles',
    'Steeplechase', 'Race Walking', 'Long Jump', 'High Jump', 'Pole Vault',
    'Triple Jump', 'Shot Put', 'Discus', 'Hammer Throw', 'Javelin',
    'Weight Throw', 'Caber Toss', 'Stone Put', 'Sheaf Toss', 'Barrel Toss',
    'Swimming', 'Diving', 'Synchronized Swimming', 'Water Skiing', 'Wakeboarding',
    'Surfing', 'Bodyboarding', 'Windsurfing', 'Kitesurfing', 'Kiteboarding',
    'Stand Up Paddling', 'Canoeing', 'Kayaking', 'Rowing', 'Sculling',
    'Dragon Boat Racing', 'Outrigger Canoeing', 'Whitewater Rafting', 'White Water Slalom', 'Ski',
    'Snowboarding', 'Freestyle Skiing', 'Alpine Skiing', 'Cross Country Skiing', 'Biathlon Skiing',
    'Ski Jumping', 'Nordic Combined', 'Speed Skating', 'Short Track Speed Skating', 'Figure Skating',
    'Synchronized Skating', 'Ice Dance', 'Curling', 'Wheelchair Curling', 'Bobsleigh',
    'Skeleton', 'Luge', 'Skateboarding', 'Skateboard Vert', 'Skateboard Street',
    'Skateboard Park', 'Skateboard Downhill', 'Roller Skating', 'Roller Derby', 'Roller Inline',
    'Parkour', 'Free Running', 'Gymnastics', 'Rhythmic Gymnastics', 'Trampoline',
    'Tumbling', 'Acrobatics', 'Rock Climbing', 'Sport Climbing', 'Bouldering',
    'Speed Climbing', 'Rope Climbing', 'Rope', 'Rappelling', 'Canyoning',
    'Caving', 'Cave Diving', 'Martial Arts', 'Karate', 'Taekwondo',
    'Judo', 'Jujutsu', 'Wrestling', 'Greco Roman', 'Catch Wrestling',
    'Sumo', 'Pankration', 'Muay Thai', 'Kickboxing', 'Boxing',
    'Bare Knuckle Boxing', 'Shadowboxing', 'Fencing', 'Epee', 'Foil',
    'Sabre', 'Modern Pentathlon', 'Equestrian', 'Dressage', 'Eventing',
    'Show Jumping', 'Barrel Racing', 'Bronc Riding', 'Bull Riding', 'Roping',
    'Steer Wrestling', 'Saddle Bronc', 'Team Roping', 'Calf Roping', 'Steer Roping',
    'Polo', 'Polocrosse', 'Mounted Archery', 'Horseball', 'Tent Pegging',
    'Kin Ball', 'Hurling', 'Camogie', 'Aussie Rules', 'Gridiron',
    'Canadian Football', 'Aussie Football', 'Gaelic Games', 'Irish Sports', 'Scottish Games',
    'Welsh Sports', 'Nordic Games', 'Basque Sports', 'Breton Sports', 'Cornish Sports',
    'Extreme Sports', 'BASE Jumping', 'Skydiving', 'Hang Gliding', 'Paragliding',
    'Ballooning', 'Parasailing', 'Zip Lining', 'Rappelling', 'Bungee Jumping',
    'Rock Running', 'Fell Running', 'Trail Running', 'Orienteering', 'Adventure Racing'
  ],

  Music: [
    'Piano', 'Guitar', 'Violin', 'Cello', 'Bass',
    'Drums', 'Percussion', 'Trumpet', 'Trombone', 'French Horn',
    'Clarinet', 'Saxophone', 'Flute', 'Oboe', 'Piccolo',
    'Harmonica', 'Accordion', 'Organ', 'Synthesizer', 'Keyboard',
    'Harp', 'Lyre', 'Mandolin', 'Ukulele', 'Banjo',
    'Sitar', 'Veena', 'Sarod', 'Tabla', 'Saz',
    'Bouzouki', 'Oud', 'Lute', 'Rebec', 'Viol',
    'Hurdy Gurdy', 'Bagpipe', 'Fiddle', 'Lyre', 'Koto',
    'Shamisen', 'Biwa', 'Shakuhachi', 'Guzheng', 'Erhu',
    'Pipa', 'Oud', 'Nay', 'Kanun', 'Ney',
    'Zurna', 'Duduk', 'Shofar', 'Alphorn', 'Conch',
    'Digeridoo', 'Bodhran', 'Bouzouki', 'Kemençe', 'Lyra',
    'Qanun', 'Aqaba', 'Alat', 'Tur', 'Aud',
    'Rondo', 'Ritmo', 'Metronome', 'Tempo', 'Rhythm',
    'Beat', 'Pulse', 'Melody', 'Harmony', 'Chord',
    'Scale', 'Key', 'Note', 'Octave', 'Interval',
    'Sharp', 'Flat', 'Natural', 'Accidental', 'Rest',
    'Whole Note', 'Half Note', 'Quarter Note', 'Eighth Note', 'Sixteenth Note',
    'Thirty Second', 'Triplet', 'Tuplet', 'Swing', 'Shuffle',
    'Rubato', 'Accelerando', 'Rallentando', 'Ritardando', 'Fermata',
    'Glissando', 'Portamento', 'Staccato', 'Legato', 'Pizzicato',
    'Arco', 'Col Legno', 'Harmonic', 'Tremolo', 'Vibrato',
    'Sostenuto', 'Appassionato', 'Dolce', 'Dolorous', 'Affettuoso',
    'Amoroso', 'Amorevole', 'Amorosamente', 'Angoscioso', 'Angosciosamente',
    'Ansioso', 'Arioso', 'Amorevolmente', 'Animatissimo', 'Animato',
    'Animando', 'Animando Subito', 'Anima', 'Animit', 'Anitta',
    'Annabile', 'Annabolita', 'Annabilissimo', 'Annabilmente', 'Annaccio',
    'Annacciato', 'Annagio', 'Annagioso', 'Annagiosamente', 'Annalmente',
    'Annalmente Sensibile', 'Annalmente Tranquillo', 'Annalmente Vago', 'Annamoli', 'Annamonia',
    'Annamonica', 'Annamonicamente', 'Annamonico', 'Annamoniel', 'Annamoniella',
    'Annamonietta', 'Annamonica Sonorità', 'Annamonica Sonorità Piena', 'Annamonica Sonorità Scura', 'Annamonica Sonorità Chiara',
    'Annamonica Sonorità Piena Gioioso', 'Annamonica Sonorità Piena Solenne', 'Annamonica Sonorità Piena Dolce', 'Annamonica Sonorità Scura Grave', 'Annamonica Sonorità Scura Nobile',
    'Annamonica Sonorità Chiara Brillante', 'Annamonica Sonorità Chiara Splendente', 'Annamonica Sonorità Chiara Vivace', 'Oratorio', 'Cantata',
    'Motet', 'Madrigal', 'Chanson', 'Carol', 'Hymn',
    'Psalm', 'Antiphon', 'Responsory', 'Liturgy', 'Mass',
    'Requiem', 'Te Deum', 'Magnificat', 'Nunc Dimittis', 'Magnificat Antiphon',
    'Compline', 'Lauds', 'Prime', 'Terce', 'Sext',
    'None', 'Vespers', 'Nocturns', 'Matins', 'Graduals'
  ],

  Food: [
    'Pizza', 'Pasta', 'Burger', 'Hot Dog', 'Sandwich',
    'Taco', 'Burrito', 'Enchilada', 'Quesadilla', 'Nachos',
    'Falafel', 'Hummus', 'Pita', 'Naan', 'Roti',
    'Chapati', 'Paratha', 'Dosa', 'Idli', 'Samosa',
    'Spring Roll', 'Egg Roll', 'Dumpling', 'Wonton', 'Ravioli',
    'Tortellini', 'Gnocchi', 'Lasagna', 'Risotto', 'Polenta',
    'Couscous', 'Quinoa', 'Bulgur', 'Barley', 'Farro',
    'Millet', 'Sorghum', 'Spelt', 'Amaranth', 'Buckwheat',
    'Soba', 'Udon', 'Ramen', 'Pho', 'Pad Thai',
    'Laksa', 'Curry', 'Vindaloo', 'Madras', 'Korma',
    'Tandoori', 'Tikka', 'Masala', 'Biryani', 'Pulao',
    'Khichdi', 'Daal', 'Chole', 'Rajma', 'Lentil',
    'Bean', 'Chickpea', 'Pea', 'Soy', 'Peanut',
    'Almond', 'Walnut', 'Cashew', 'Pecan', 'Pistachio',
    'Hazelnut', 'Macadamia', 'Brazil Nut', 'Pine Nut', 'Sunflower Seed',
    'Pumpkin Seed', 'Sesame Seed', 'Poppy Seed', 'Caraway Seed', 'Dill Seed',
    'Cumin Seed', 'Coriander Seed', 'Fennel Seed', 'Fenugreek Seed', 'Nigella Seed',
    'Mustard Seed', 'Black Seed', 'Flax Seed', 'Chia Seed', 'Hemp Seed',
    'Pumpkin Pie', 'Apple Pie', 'Cherry Pie', 'Lemon Pie', 'Key Lime Pie',
    'Pecan Pie', 'Blueberry Pie', 'Strawberry Pie', 'Rhubarb Pie', 'Cream Pie',
    'Meringue Pie', 'Coconut Pie', 'Custard Pie', 'Pumpkin Pie', 'Sweet Potato Pie',
    'Pot Pie', 'Chicken Pot Pie', 'Beef Pot Pie', 'Seafood Pot Pie', 'Vegetable Pot Pie',
    'Turkey Pot Pie', 'Cornish Hen Pot Pie', 'Quail Pot Pie', 'Mushroom Pot Pie', 'Spinach Pot Pie',
    'Tomato Pie', 'Onion Pie', 'Leek Pie', 'Broccoli Pie', 'Cauliflower Pie',
    'Cabbage Pie', 'Zucchini Pie', 'Eggplant Pie', 'Asparagus Pie', 'Artichoke Pie',
    'Carrot Pie', 'Beet Pie', 'Turnip Pie', 'Parsnip Pie', 'Celery Root Pie',
    'Radish Pie', 'Kohlrabi Pie', 'Rutabaga Pie', 'Celeriac Pie', 'Fennel Pie',
    'Leek Pie', 'Scallion Pie', 'Garlic Pie', 'Onion Pie', 'Shallot Pie',
    'Bread', 'White Bread', 'Wheat Bread', 'Rye Bread', 'Pumpernickel Bread',
    'Sourdough Bread', 'Italian Bread', 'French Bread', 'Baguette', 'Ciabatta',
    'Focaccia', 'Flatbread', 'Naan Bread', 'Pita Bread', 'Tortilla',
    'Corn Tortilla', 'Flour Tortilla', 'Spinach Tortilla', 'Whole Wheat Tortilla', 'Roti',
    'Chapati', 'Paratha', 'Naan', 'Puri', 'Bhatura',
    'Dosa', 'Uttapam', 'Idli', 'Appam', 'Puttu',
    'Crepe', 'Galette', 'Blini', 'Pancake', 'Waffle',
    'Crumpet', 'English Muffin', 'Bagel', 'Bialy', 'Kaiser Roll',
    'Bun', 'Croissant', 'Danish', 'Pastry', 'Donut',
    'Muffin', 'Scone', 'Biscuit', 'Cookie', 'Cracker'
  ],

  Cities: [
    'Tokyo', 'Beijing', 'Shanghai', 'Mumbai', 'Delhi',
    'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
    'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose',
    'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte',
    'San Francisco', 'Indianapolis', 'Seattle', 'Denver', 'Boston',
    'El Paso', 'Memphis', 'Nashville', 'Detroit', 'Oklahoma City',
    'Portland', 'Las Vegas', 'Louisville', 'Baltimore', 'Milwaukee',
    'Albuquerque', 'Tucson', 'Fresno', 'Sacramento', 'Kansas City',
    'Long Beach', 'Mesa', 'Virginia Beach', 'Atlanta', 'Miami',
    'New Orleans', 'Honolulu', 'Anaheim', 'Tampa', 'Aurora',
    'Santa Ana', 'Riverside', 'Bakersfield', 'Stockton', 'Irvine',
    'Laredo', 'Chula Vista', 'Irving', 'Norfolk', 'Garland',
    'Glendale', 'Fremont', 'Modesto', 'Fontana', 'Moreno Valley',
    'Shreveport', 'Amarillo', 'Brownsville', 'Huntington Beach', 'Tallahassee',
    'San Bernardino', 'Plano', 'Birmingham', 'Baton Rouge', 'Winston Salem',
    'Huntsville', 'Garland', 'Fremont', 'Glendale', 'Oxnard',
    'Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton',
    'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener',
    'London', 'Paris', 'Berlin', 'Madrid', 'Rome',
    'Moscow', 'Istanbul', 'Cairo', 'Bangkok', 'Singapore',
    'Hong Kong', 'Seoul', 'Busan', 'Mexico City', 'São Paulo',
    'Rio de Janeiro', 'Buenos Aires', 'Lima', 'Bogotá', 'Caracas',
    'Santiago', 'Havana', 'Kingston', 'Port of Spain', 'Nassau',
    'Santo Domingo', 'San Juan', 'Montego Bay', 'Cancún', 'Playa del Carmen',
    'Acapulco', 'Mazatlán', 'Puerto Vallarta', 'Cozumel', 'Los Cabos',
    'Cabo San Lucas', 'San Jose del Cabo', 'Todos Santos', 'La Paz', 'Loreto',
    'Hermosillo', 'Ciudad Obregón', 'Navojoa', 'Guaymas', 'Nogales',
    'Culiacán', 'Durango', 'Torreón', 'Saltillo', 'Monterrey',
    'Guadalajara', 'Querétaro', 'San Luis Potosí', 'Aguascalientes', 'Zacatecas',
    'Chihuahua', 'Ciudad Juárez', 'Nuevo Laredo', 'Reynosa', 'Matamoros',
    'Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford',
    'Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee', 'Perth',
    'Inverness', 'Stirling', 'Dumfries', 'Ayr', 'Kilmarnock',
    'Cardiff', 'Swansea', 'Newport', 'Colwyn Bay', 'Caernarfon',
    'Amsterdam', 'Rotterdam', 'Utrecht', 'Groningen', 'Antwerp',
    'Brussels', 'Ghent', 'Bruges', 'Liège', 'Charleroi',
    'Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne',
    'Vienna', 'Prague', 'Budapest', 'Bratislava', 'Warsaw',
    'Krakow', 'Gdańsk', 'Wrocław', 'Poznań', 'Łódź',
    'Copenhagen', 'Gothenburg', 'Stockholm', 'Hamburg', 'Munich',
    'Stuttgart', 'Frankfurt', 'Cologne', 'Düsseldorf', 'Dortmund',
    'Essen', 'Leipzig', 'Dresden', 'Nuremberg', 'Hannover'
  ],

  Colors: [
    'Red', 'Blue', 'Green', 'Yellow', 'Orange',
    'Purple', 'Pink', 'Brown', 'Black', 'White',
    'Gray', 'Grey', 'Silver', 'Gold', 'Beige',
    'Tan', 'Cream', 'Ivory', 'Maroon', 'Navy',
    'Teal', 'Cyan', 'Magenta', 'Turquoise', 'Olive',
    'Lime', 'Coral', 'Salmon', 'Peach', 'Lavender',
    'Violet', 'Indigo', 'Scarlet', 'Crimson', 'Ruby',
    'Garnet', 'Cherry', 'Blood Red', 'Burgundy', 'Wine',
    'Rose', 'Fuchsia', 'Mauve', 'Plum', 'Lilac',
    'Orchid', 'Iris', 'Violet', 'Periwinkle', 'Amethyst',
    'Sapphire', 'Cobalt', 'Azure', 'Sky Blue', 'Navy Blue',
    'Royal Blue', 'Steel Blue', 'Slate Blue', 'Powder Blue', 'Light Blue',
    'Periwinkle', 'Cornflower', 'Dodger Blue', 'Deep Blue', 'Midnight Blue',
    'Hunter Green', 'Forest Green', 'Dark Green', 'Olive Green', 'Sage Green',
    'Moss Green', 'Sea Green', 'Spring Green', 'Lawn Green', 'Lime Green',
    'Chartreuse', 'Yellow Green', 'Khaki', 'Gold', 'Golden',
    'Honey', 'Lemon', 'Cream', 'Pale Yellow', 'Butter',
    'Sunflower', 'Canary', 'Mustard', 'Ochre', 'Burnt Sienna',
    'Umber', 'Raw Sienna', 'Burnt Orange', 'Rust', 'Terracotta',
    'Copper', 'Bronze', 'Brass', 'Chocolate', 'Coffee',
    'Espresso', 'Sepia', 'Tan', 'Sand', 'Wheat',
    'Straw', 'Hazel', 'Chestnut', 'Mahogany', 'Walnut',
    'Cedar', 'Oak', 'Elm', 'Ash', 'Hickory',
    'Maple', 'Pine', 'Spruce', 'Fir', 'Juniper',
    'Ebony', 'Jet', 'Onyx', 'Obsidian', 'Coal',
    'Charcoal', 'Slate', 'Graphite', 'Pearl', 'Platinum',
    'Steel', 'Aluminum', 'Tin', 'Nickel', 'Chrome',
    'Iron', 'Copper', 'Bronze', 'Brass', 'Gold',
    'Silver', 'Mercury', 'Quicksilver', 'Mirror', 'Reflective',
    'Metallic', 'Shiny', 'Glossy', 'Matte', 'Satin',
    'Velvet', 'Suede', 'Wool', 'Cotton', 'Linen',
    'Silk', 'Satin', 'Sheen', 'Luster', 'Sheen',
    'Pearlescent', 'Iridescent', 'Holographic', 'Neon', 'Fluorescent',
    'Luminescent', 'Phosphorescent', 'Bioluminescent', 'Incandescent', 'Radiant',
    'Glowing', 'Shimmering', 'Sparkling', 'Twinkling', 'Glistening',
    'Gleaming', 'Glinting', 'Flashing', 'Flickering', 'Fading',
    'Dimming', 'Brightening', 'Darkening', 'Lightening', 'Shadowing',
    'Highlight', 'Shadow', 'Shade', 'Tint', 'Tone',
    'Hue', 'Saturation', 'Brightness', 'Lightness', 'Value',
    'Contrast', 'Gradient', 'Gradient Fade', 'Blend', 'Mix',
    'Blend Together', 'Merge', 'Fusion', 'Combined', 'Unified',
    'Unified Color', 'Complementary', 'Analogous', 'Triadic', 'Tetradic',
    'Monochromatic', 'Achromatic', 'Chromatic', 'Neutral', 'Pastel'
  ],

  Vehicles: [
    'Car', 'Truck', 'Bus', 'Motorcycle', 'Bicycle',
    'Tricycle', 'Scooter', 'Skateboard', 'Rollerblades', 'Unicycle',
    'Motorhome', 'RV', 'Camper', 'Trailer', 'Caravan',
    'Sedan', 'Coupe', 'Convertible', 'Hatchback', 'Wagon',
    'Station Wagon', 'Crossover', 'SUV', 'Jeep', 'Van',
    'Minivan', 'Pickup Truck', 'Flatbed Truck', 'Dump Truck', 'Tanker Truck',
    'Box Truck', 'Refrigerated Truck', 'Cement Mixer', 'Tow Truck', 'Garbage Truck',
    'Fire Truck', 'Ambulance', 'Police Car', 'Patrol Car', 'Cruiser',
    'Taxi', 'Uber', 'Lyft', 'Limo', 'Limousine',
    'Sedan', 'Stretch Limo', 'Party Bus', 'Charter Bus', 'School Bus',
    'Double Decker', 'Trolleybus', 'Trolley', 'Streetcar', 'Tram',
    'Cable Car', 'Funicular', 'Monorail', 'Maglev', 'Light Rail',
    'Commuter Rail', 'High Speed Rail', 'Bullet Train', 'Steam Train', 'Freight Train',
    'Passenger Train', 'Locomotive', 'Box Car', 'Flatcar', 'Tank Car',
    'Gondola', 'Covered Wagon', 'Caboose', 'Tender Car', 'Sleeper Car',
    'Observation Car', 'Dining Car', 'Baggage Car', 'Mail Car', 'Express Car',
    'Private Car', 'Parlor Car', 'Club Car', 'Lounge Car', 'Game Car',
    'Library Car', 'Barber Shop Car', 'Shower Car', 'Bath Car', 'Kitchen Car',
    'Laundry Car', 'Office Car', 'Hospital Car', 'Jail Car', 'Prison Car',
    'Penitentiary Car', 'Execution Car', 'Atomic Car', 'Nuclear Car', 'Radiation Car',
    'Contaminated Car', 'Hazmat Car', 'Dangerous Goods Car', 'Hazardous Materials Car', 'Special Equipment Car',
    'Specialized Car', 'Custom Car', 'Hot Rod', 'Custom Built', 'One Off',
    'Prototype', 'Concept Car', 'Experimental Car', 'Research Car', 'Test Car',
    'Race Car', 'Formula 1', 'Dragster', 'Funny Car', 'Stockcar',
    'Rally Car', 'Off Road Vehicle', 'Dune Buggy', 'Sand Buggy', 'Go Kart',
    'Kart', 'ATV', 'Quad', 'Four Wheeler', 'Snowmobile',
    'Jetski', 'Personal Watercraft', 'Hovercraft', 'Amphibious Vehicle', 'Tank',
    'Military Tank', 'Armored Vehicle', 'Personnel Carrier', 'Troop Carrier', 'Cargo Vehicle',
    'Supply Truck', 'Ambulance', 'Medical Vehicle', 'Mobile Hospital', 'Clinic Van',
    'Mobile Home', 'Tiny House', 'Food Truck', 'Taco Truck', 'Coffee Truck',
    'Ice Cream Truck', 'Delivery Truck', 'Amazon Truck', 'UPS Truck', 'FedEx Truck',
    'Mail Truck', 'Postal Vehicle', 'Express Mail Truck', 'Package Truck', 'Cargo Plane',
    'Airplane', 'Jet', 'Aircraft', 'Helicopter', 'Gyrocopter',
    'Seaplane', 'Floatplane', 'Flying Boat', 'Glider', 'Hot Air Balloon',
    'Blimp', 'Zeppelin', 'Airship', 'Hovercraft', 'Drone',
    'Drone Aircraft', 'Unmanned Aircraft', 'UAV', 'Flying Vehicle', 'Spacecraft',
    'Rocket', 'Space Shuttle', 'Space Station Module', 'Lunar Module', 'Mars Rover',
    'Rover', 'Space Vehicle', 'Interplanetary Vehicle', 'Sub Orbital Vehicle', 'Orbital Vehicle'
  ],

  Technology: [
    'Computer', 'Laptop', 'Desktop', 'Tablet', 'Smartphone',
    'Phone', 'Mobile Phone', 'Feature Phone', 'Flip Phone', 'Rotary Phone',
    'Corded Phone', 'Cordless Phone', 'Walkie Talkie', 'Two Way Radio', 'Ham Radio',
    'CB Radio', 'Satellite Phone', 'VoIP Phone', 'Internet Phone', 'Skype',
    'Zoom', 'Google Meet', 'Teams', 'Slack', 'Discord',
    'WhatsApp', 'Telegram', 'WeChat', 'Viber', 'Signal',
    'Messenger', 'iMessage', 'Email', 'Gmail', 'Outlook',
    'Yahoo Mail', 'Hotmail', 'AOL Mail', 'ProtonMail', 'Tutanota',
    'Server', 'Mainframe', 'Supercomputer', 'Workstation', 'Gaming PC',
    'Console', 'PlayStation', 'Xbox', 'Nintendo', 'Arcade Machine',
    'Atari', 'Commodore', 'Apple II', 'BBC Micro', 'Sinclair',
    'ZX Spectrum', 'Amstrad', 'Dragon', 'TRS 80', 'VIC 20',
    'Commodore 64', 'Sega Genesis', 'Sega Dreamcast', 'Game Boy', 'Game Gear',
    'Lynx', 'Virtual Boy', 'Sega Game Gear', 'Atari Lynx', 'Turbo Express',
    'Game & Watch', 'Mattel Auto Race', 'Milton Bradley Auto Race', 'Fairchild Channel F', 'Intellivision',
    'ColecoVision', 'Magnavox Odyssey', 'Pong', 'Betamax', 'VHS',
    'VCR', 'DVD Player', 'Blu Ray Player', '4K Player', 'Media Player',
    'VHS Tape', 'Cassette Tape', 'Floppy Disk', 'ZIP Disk', 'USB Drive',
    'Thumb Drive', 'Flash Drive', 'Memory Stick', 'SD Card', 'MicroSD Card',
    'CompactFlash', 'CF Card', 'PCMCIA Card', 'PC Card', 'ExpressCard',
    'Thunderbolt', 'USB C', 'Lightning Cable', 'Micro USB', '30 Pin Connector',
    'DVI', 'HDMI', 'DisplayPort', 'VGA', 'Composite',
    'RCA Cable', 'Coaxial Cable', 'Ethernet Cable', 'Fiber Optic Cable', 'Telephone Cable',
    'Power Cable', 'Extension Cord', 'Power Strip', 'Surge Protector', 'UPS',
    'Uninterruptible Power Supply', 'Generator', 'Solar Panel', 'Wind Turbine', 'Battery',
    'Lithium Battery', 'Alkaline Battery', 'Rechargeable Battery', 'Solar Battery', 'Backup Battery',
    'Capacitor', 'Resistor', 'Transistor', 'Diode', 'LED',
    'LCD', 'OLED', 'QLED', 'Mini LED', 'E Ink',
    'Monitor', 'Projector', 'TV', 'Plasma TV', 'Smart TV',
    '4K TV', '8K TV', 'CURVED TV', 'HDR TV', 'Curved Monitor',
    'Curved Display', 'Touchscreen', 'Touchpad', 'Trackpad', 'Track Ball',
    'Mouse', 'Wireless Mouse', 'Gaming Mouse', 'Trackball', 'Stylus',
    'Pen', 'Digital Pen', 'Graphics Tablet', 'Wacom Tablet', 'Digitizer',
    'Keyboard', 'Mechanical Keyboard', 'Wireless Keyboard', 'Laptop Keyboard', 'Ergonomic Keyboard',
    'Speaker', 'Headphones', 'Earbuds', 'Headset', 'Earphone',
    'Microphone', 'Condenser Mic', 'Dynamic Mic', 'USB Mic', 'Bluetooth Speaker',
    'Soundbar', 'Home Theater System', 'Surround Sound', 'Subwoofer', 'Amplifier'
  ]
};

